#!/bin/sh

sxhkd &

polybar dapine &

bspc monitor -d code web III IV V VI

bspc config border_width        4
bspc config window_gap          8
if [ $PYWAL ]
then
    source "${HOME}/.cache/wal/colors.sh"
    bspc config normal_border_color "$color1"
    bspc config active_border_color "$color2"
    bspc config focused_border_color "$color15"
    bspc config presel_feedback_color "$color1"
else
    bspc config normal_border_color "#30302f"
    bspc config active_border_color "#fabd2f"
    bspc config focused_border_color "#ebdbb2"
fi

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
