#! /bin/sh

sxhkd &

$HOME/.config/polybar/launch.sh

. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d code web III IV V VI

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
