#!/bin/sh

sxhkd &

polybar dapine &

bspc monitor -d code web III IV V VI

bspc config border_width        2
bspc config window_gap          8
xsetroot -solid "#183A37"
bspc config normal_border_color "#30302f"
bspc config active_border_color "#fabd2f"
bspc config focused_border_color "#ebdbb2"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
