#! /bin/sh

sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor -d code web III IV V VI

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#93a1a1"
bspc config focused_border_color "#268bd2"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
