#!/bin/sh

# a script for backup files and directories to a git repository
# for now it just copies files to a specific directory. i dont use
# more than 40% of my disk anyway ¯\_(ツ)_/¯

# must be a git repo
backupdir="$HOME/.backup/"

# folders and files to be backup'd
itemlist="$HOME/Pictures $HOME/Documents"

copy () {
    cp -r $1 $backupdir
}

sync () {
    cd $backupdir
    git fetch
    git add -A
    git commit -m "$(echo $(date -u +%Y-%m-%d:%H-%M-%S-UTC)@$(hostname))"
    git push origin master
}

doit () {
    for i in $itemlist
    do
        copy $i
    done

    sync
}

doit
