#!/bin/sh

case "$1" in up) pactl set-sink-volume @DEFAULT_SINK@ +2% && notify-send -t 1000 "$(amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }')";;
             down) pactl set-sink-volume @DEFAULT_SINK@ -2% && notify-send -t 1000 "$(amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }')";;
             mute) pactl set-sink-mute @DEFAULT_SINK@ toggle && notify-send -t 1000 "$(amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }')";;
esac

